name: Auto Build Geo-Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - main
    paths:
      - "config.json"

permissions:
  contents: write

jobs:
  build:
    name: Generate Mihomo and Sing-box Rules
    runs-on: ubuntu-latest
    env:
      CURL: "curl -fsSL --retry 3 --retry-delay 2 --retry-connrefused"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Checkout Loyalsoldier/geoip builder
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/geoip
          path: geoip-src
          fetch-depth: 1

      - name: Build geoip binary
        working-directory: geoip-src
        run: |
          set -euo pipefail
          go mod download
          go build -o geoip

      - name: Download MaxMind databases & Custom lists
        run: |
          set -euo pipefail
          mkdir -p geoip-src/geolite2

          ${{ env.CURL }} -o /tmp/GeoLite2-Country-CSV.zip https://github.com/Loyalsoldier/geoip/raw/release/GeoLite2-Country-CSV.zip
          ${{ env.CURL }} -o /tmp/GeoLite2-ASN-CSV.zip https://dl.netsyms.net/dbs/geolite2/GeoLite2-ASN-CSV.zip

          unzip -j /tmp/GeoLite2-Country-CSV.zip '*/GeoLite2-Country-Locations-en.csv' '*/GeoLite2-Country-Blocks-IPv4.csv' '*/GeoLite2-Country-Blocks-IPv6.csv' -d geoip-src/geolite2
          unzip -j /tmp/GeoLite2-ASN-CSV.zip '*/GeoLite2-ASN-Blocks-IPv4.csv' '*/GeoLite2-ASN-Blocks-IPv6.csv' -d geoip-src/geolite2

          ${{ env.CURL }} -o geoip-src/geolite_ru.lst https://raw.githubusercontent.com/hydraponique/countrydb/refs/heads/main/output/geolite2-geo-whois-asn-country-ipv4/ru.lst
          ${{ env.CURL }} -o geoip-src/geolite_by.lst https://raw.githubusercontent.com/hydraponique/countrydb/refs/heads/main/output/geolite2-geo-whois-asn-country-ipv4/by.lst

      - name: Run Loyalsoldier compiler
        run: |
          set -euo pipefail
          # Копируем твой config.json из корня репозитория в папку утилиты
          cp config.json geoip-src/config.json
          cd geoip-src
          ./geoip convert -c config.json

      - name: Push generated rules to repository
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add geoip/
          
          git diff --cached --quiet || (git commit -m "Update GeoIP rules ($(date +%Y-%m-%d))" && git push origin HEAD:main)
